- name:  Install tomcat7
  apt: name=tomcat7 state=present update_cache=yes cache_valid_time=3600

- name: Enforce Java 7 use for tomcat
  lineinfile: 
    dest: /etc/default/tomcat7
    regexp: '#JAVA_HOME=/usr/lib/jvm/openjdk-6-jdk'
    line: 'JAVA_HOME=/usr/lib/jvm/java-7-oracle-cloudera'
    state: present
  register: tomcat7_java7
  
# handle user database
- include: populatedb.yml database=seqware_meta_db
    
# handle test database
- include: populatedb.yml database=test_seqware_meta_db

- name: Determine Seqware Version 
  shell: 'ls ~seqware/gitroot/seqware/seqware-distribution/target/seqware-distribution-*-full.jar | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+(-SNAPSHOT)?" | head -1'
  register: det_seqware_version
  changed_when: false

# this part sucks
# We are doing a fetch and then copy because hard linking always detects a change and redeploys
# soft-linking requires the tomcat7 user to have permission into the seqware directory which is not ideal
# there is no module for copying from one place on the remote file system to another, so fetching and then pushing again is the current approach
- name:  Fetch jars and xml config files
  fetch: fail_on_missing=yes src={{ item.src }} dest=/tmp/fetched/{{ ansible_eth0.ipv4.address }}/ flat=yes
  with_items:
     - { src: '/home/seqware/gitroot/seqware/seqware-webservice/target/seqware-webservice-{{ det_seqware_version.stdout }}.war' }
     - { src: '/home/seqware/gitroot/seqware/seqware-webservice/target/seqware-webservice-{{ det_seqware_version.stdout }}.xml' }
     - { src: '/home/seqware/gitroot/seqware/seqware-portal/target/seqware-portal-{{ det_seqware_version.stdout }}.war' }
     - { src: '/home/seqware/gitroot/seqware/seqware-portal/target/seqware-portal-{{ det_seqware_version.stdout }}.xml' }

- name:  Copy up jars and xml config files
  copy: src={{ item.src }} dest={{ item.dest }} owner=tomcat7
  with_items:
     - { src: '/tmp/fetched/{{ ansible_eth0.ipv4.address }}/seqware-webservice-{{ det_seqware_version.stdout }}.war', dest: '/var/lib/tomcat7/webapps/SeqWareWebService.war' }
     - { src: '/tmp/fetched/{{ ansible_eth0.ipv4.address }}/seqware-webservice-{{ det_seqware_version.stdout }}.xml', dest: '/etc/tomcat7/Catalina/localhost/SeqWareWebService.xml' }
     - { src: '/tmp/fetched/{{ ansible_eth0.ipv4.address }}/seqware-portal-{{ det_seqware_version.stdout }}.war', dest: '/var/lib/tomcat7/webapps/SeqWarePortal.war' }
     - { src: '/tmp/fetched/{{ ansible_eth0.ipv4.address }}/seqware-portal-{{ det_seqware_version.stdout }}.xml', dest: '/etc/tomcat7/Catalina/localhost/SeqWarePortal.xml' }
  register: tomcatconf
  
- name:  Tomcat restart
  service: name=tomcat7 state=restarted
  when: tomcatconf.changed or tomcat7_java7.changed
