---
# Add one of the following: vagrant-aws, vagrant-openstack-plugin or vagrant-vcloud
vagrant_plugin: "vagrant-aws" 
vagrant_plugin_version: "0.5.0"
# The git repo branches, if you're working in production then use "master"
bindle_git_branch: "master"

# Add the name of the template Bindle config you will work with (e.g. "openstack.cfg")
bindle_config: "aws.cfg"
