---
# file: roles/grid-engine/tasks/master.yml

- name: SGE | Install gridengine-qmon
  apt: pkg=gridengine-qmon state=present update_cache=yes cache_valid_time=3600

- name: SGE | Install gridengine-master 
  apt: pkg=gridengine-master state=present update_cache=yes cache_valid_time=3600

- name: SGE | Configure master
  command: qconf -as {{ inventory_hostname }}
  register: configure_master_as
  changed_when: not 'already exists' in configure_master_as.stderr
  
- name: SGE | Make a directory for our SGE templates
  file: state=directory path=/etc/gridengine/templates mode=0744
  
# setup memory as a consumable resource
- name: SGE | Template memory configuration file
  template: src=sc.j2 dest=/etc/gridengine/templates/sge_sc
  register: memory_template
  
- name: SGE | Setup memory as consumable resource
  command: qconf -Mc /etc/gridengine/templates/sge_sc
  when: memory_template.changed
  register: memory_consumable
  changed_when: not 'Complex attribute configuration has not been changed' in memory_consumable.stderr

# Be careful when adding the user. First get he current list, and only add if it isn't
# already present.
- name: SGE | Check current user list
  shell: qconf -su users | grep -E "^entries" | cut -f2 -d " "
  register: sge_current_users
  changed_when: false

- name: SGE | Add the capsid user
  command: qconf -au capsid users
  when: not 'capsid' in sge_current_users.stdout.split(',')
  
# loop through and template worker hosts
- name: SGE | Generate execution host templates
  template: src=execution_host.j2 dest=/etc/gridengine/templates/sge_execution_host_{{ item }}.sh mode=0555
  when: not single_node
  with_items: groups.worker
  register: execution_host_template

# loop through and setup worker hosts, if this was better it would modify existing hosts as well instead of ignoring errors
- name: SGE | Add worker hosts as execution hosts
  shell: export EDITOR=/etc/gridengine/templates/sge_execution_host_{{ item }}.sh && qconf -ae
  with_items: groups.worker
  when: execution_host_template.changed 
  ignore_errors: yes
  
  # add the master as an execution host if we only have one node
- name: SGE | Single node execution host templates
  template: src=execution_host.j2 dest=/etc/gridengine/templates/sge_execution_host_master.sh mode=0555
  register: execution_host_template
  when: not single_node

# loop through and setup worker hosts, if this was better it would modify existing hosts as well instead of ignoring errors
- name: SGE | Single node host as execution hosts
  shell: export EDITOR=/etc/gridengine/templates/sge_execution_host_master.sh && qconf -ae
  when: execution_host_template.changed
  ignore_errors: yes
  when: not single_node

# Again, we don't want to do this if it already exists, never counts as a change registering variables
- name: SGE | Check current host groups
  command: qconf -shgrpl
  ignore_errors: yes
  register: sge_current_host_groups
  changed_when: false

# The template now handles the hostlist properly
- name: SGE | Template host group configuration
  template: src=ahgrp.j2 dest=/etc/gridengine/templates/sge_ahgrp
  when: not '@allhosts' in sge_current_host_groups.stdout_lines

- name: SGE | Add the host group configuration
  command: qconf -Ahgrp /etc/gridengine/templates/sge_ahgrp
  when: not '@allhosts' in sge_current_host_groups.stdout_lines

# Again, we don't want to do this if it already exists
- name: SGE | Check current queues
  command: qconf -sql
  ignore_errors: yes
  register: sge_current_queues
  changed_when: false

# template handles hostlist, worker queue slots, target load average
- name: SGE | Template main queue
  template: src=aq.j2 dest=/etc/gridengine/templates/sge_aq
  when: not 'main.q' in sge_current_queues.stdout_lines
  register: main_queue_template

- name: SGE | Add main queue
  command: qconf -Aq /etc/gridengine/templates/sge_aq
  when: not 'main.q' in sge_current_queues.stdout_lines or main_queue_template.changed

- name: SGE | Check parallel environment status
  command: qconf -sp serial
  ignore_errors: yes
  when: grid_engine_master == True
  register: sge_parallel_env
  changed_when: false

- name: SGE | Template serial parallel environment file
  template: src=serial_profile.j2 dest=/etc/gridengine/templates/sge_serial_profile
  register: serial_profile
  
# Again, if this was better, we would re-create the environment if there were changes in the template
- name: SGE | Setup serial profile environment
  command: $item
  with_items:
      - qconf -Ap /etc/gridengine/templates/sge_serial_profile
      - qconf -aattr queue pe_list serial main.q
  when: serial_profile.changed
  ignore_errors: yes